PUT http://localhost:3000/api/articles/5
content-type: application/json

{
   "picture": "item10.jpg",
    "title": "Как перестать беспокоиться и начать жить",
    "announce": "Маленькими шагами. sБороться с прокрастинацией несложно. Просто действуйте. ",
    "fullText": "Игры и программирование разные вещи. Золотое сечение — соотношение двух величин гармоническая пропорция. Простые ежедневные упражнения помогут достичь успеха. Этот смартфон — настоящая находка. Процессор заслуживает особого внимания. Так ли это на самом деле? Достичь успеха помогут ежедневные повторения. Собрать камни бесконечности легко если вы прирожденный герой. Не стоит идти в программисты если вам нравится только игры. Освоить вёрстку несложно. Вы можете достичь всего. Первая большая ёлка была установлена только в 1938 году. Из под его пера вышло 8 платиновых альбомов. Для начала просто соберитесь. Он написал больше 30 хитов. Это прочная древесина. Как начать действовать? Ёлки — это не просто красивое дерево. Бороться с прокрастинацией несложно. Он обязательно понравится геймерам со стажем. Программировать не настолько сложно как об этом говорят. Рок-музыка всегда ассоциировалась с протестами. Возьмите книгу новую книгу и закрепите все упражнения на практике.",
    "userId": 2
}
