POST http://localhost:8080/login HTTP/1.1
content-type: multipart/form-data

------WebKitFormBoundaryl0BfwBO2b46iJoYk
Content-Disposition: form-data; name="email"

mail@mail.ru
------WebKitFormBoundaryl0BfwBO2b46iJoYk
Content-Disposition: form-data; name="password"

111
------WebKitFormBoundaryl0BfwBO2b46iJoYk--


